spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/marcidb
    username: marci
    password: marci@123
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgresSQLDialect