logging:
  level:
    root: INFO
    net.marci: INFO

server:
  port: 7080

spring:
  datasource:
    server:
      host: localhost
      port: 5432
    url: jdbc:postgresql://${spring.datasource.server.host}:${spring.datasource.server.port}/marcidb
    username: marci
    password: marci@123
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  ansi:
    enabled: DETECT